- hosts: localhost
  become: false
  collections:
    - tuxinvader.launchpad

  tasks:

    - name: Upload Kernel packages to PPA
      ppa_upload_package:
        source_changes: /usr/local/src/cod/debs/v5.15.71/linux-generic-5.15_5.15.71_source.changes
        ppa: ~tuxinvader/my-random-ppa
      
