- hosts: localhost
  become: false
  collections:
    - tuxinvader.launchpad

  environment:
    LP_ACCESS_TOKEN: "{{ secret_access_token }}"
    LP_ACCESS_SECRET: "{{ secret_access_secret }}"

  tasks:
      
    - name: Prune my-random PPA to 2 packages
      prune_ppa:
        name: my-random-ppa
        project: ~tuxinvader
        max_sources: 2


