- hosts: localhost
  become: false
  collections:
    - tuxinvader.launchpad

  environment:
    LP_ACCESS_TOKEN: "{{ secret_access_token }}"
    LP_ACCESS_SECRET: "{{ secret_access_secret }}"

  tasks:

    - name: Get build records for linux-generic-5.19
      build_record_info:
        project: ~tuxinvader
        ppa: my-random-ppa
        source_name: linux-generic-5.19
        #source_version: 5.19.12
        #build_id: 24510990
        #build_id: 24505969
        time_frame: 9999999
