- hosts: localhost
  become: false
  collections:
    - tuxinvader.launchpad

  environment:
    LP_ACCESS_TOKEN: "{{ secret_access_token }}"
    LP_ACCESS_SECRET: "{{ secret_access_secret }}"

  tasks:

    - name: Test PPA Info
      ppa_info:
        project: ~tuxinvader
        name: jammy-mainline
      
    - name: Test PPA Info (random)
      ppa_info:
        project: ~tuxinvader
        name: my-random-ppa
        source_filter: '*'
      
