- hosts: localhost
  become: false
  collections:
    - tuxinvader.launchpad

  environment:
    LP_ACCESS_TOKEN: "{{ secret_access_token }}"
    LP_ACCESS_SECRET: "{{ secret_access_secret }}"

  tasks:

    - name: Prune mainline PPA to 2 packages
      prune_ppa:
        name: lts-mainline
        project: ~tuxinvader
        max_sources: 2
      
    - name: Prune mainline-longterm PPA to 4 packages
      prune_ppa:
        name: lts-mainline-longterm
        project: ~tuxinvader
        max_sources: 4

