- hosts: localhost
  become: false
  collections:
    - tuxinvader.launchpad

  environment:
    LP_ACCESS_TOKEN: "{{ secret_access_token }}"
    LP_ACCESS_SECRET: "{{ secret_access_secret }}"

  tasks:

    - name: Ensure kernel 6.0-rc7 is removed
      source_package:
        project: ~tuxinvader
        ppa: my-random-ppa
        name: linux-generic
        version: "6.0-rc7"
        match: starts_with
        ensure: absent

    - name: Ensure kernel 5.19.12 is added
      source_package:
        project: ~tuxinvader
        ppa: my-random-ppa
        name: linux-generic-5.19
        version: 5.19.12
        ensure: present
        source_changes: /usr/local/src/cod/debs/v5.19.12/linux-generic-5.19_5.19.12_source.changes