- hosts: localhost
  become: false
  collections:
    - tuxinvader.launchpad

  tasks:

    - name: Test User Info
      user_info:
        name: tuxinvader
        authorize: no
      register: tux
      
